//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_User
    {
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int phoneNumber { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string profilePicture { get; set; }
        public string residence { get; set; }
        public int radius { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string itemViewingMethod { get; set; }
    }
}
